# Generated by Django 4.2.4 on 2023-09-16 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0002_remove_animale_id_animale_id_animale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestaadozione',
            name='utente',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to='adozione.utente'),
        ),
    ]
