# Generated by Django 4.2.4 on 2023-09-16 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0003_richiestaadozione_utente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='richiestaadozione',
            name='id',
        ),
        migrations.AddField(
            model_name='richiestaadozione',
            name='ID_richiestaAdozione',
            field=models.CharField(default=0, max_length=30, primary_key=True, serialize=False),
        ),
    ]
