# Generated by Django 4.2.4 on 2023-09-16 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adozione', '0004_remove_richiestaadozione_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='cognome',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='password',
        ),
        migrations.AddField(
            model_name='utente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
