# Generated by Django 4.2.4 on 2023-09-16 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0005_remove_utente_cognome_remove_utente_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utente',
            name='user',
        ),
        migrations.AddField(
            model_name='utente',
            name='cognome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utente',
            name='email',
            field=models.CharField(default='a@email.it', max_length=400),
        ),
        migrations.AddField(
            model_name='utente',
            name='nome',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='utente',
            name='password',
            field=models.CharField(default='Password', max_length=30),
        ),
    ]
