# Generated by Django 4.2.4 on 2023-09-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0006_remove_utente_user_utente_cognome_utente_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utente',
            name='confermaPassword',
            field=models.CharField(default='Password', max_length=30),
        ),
    ]
