# Generated by Django 4.2.4 on 2023-09-17 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adozione', '0007_utente_confermapassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaadozione',
            name='utente',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
