# Generated by Django 4.2.4 on 2023-09-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0010_alter_richiestaadozione_id_richiestaadozione'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiestaadozione',
            name='richiesta',
            field=models.CharField(default='in attesa', max_length=400),
        ),
    ]
