# Generated by Django 4.2.4 on 2023-09-19 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0011_richiestaadozione_richiesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaadozione',
            name='animale',
            field=models.ForeignKey(default='Animale', null=True, on_delete=django.db.models.deletion.CASCADE, to='adozione.animale'),
        ),
    ]
