# Generated by Django 4.2.4 on 2023-09-19 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adozione', '0015_alter_richiestaadozione_animale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animale',
            name='ID_animale',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='richiestaadozione',
            name='animale',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='adozione.animale'),
        ),
    ]
