# Generated by Django 4.2.4 on 2023-08-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razza', models.CharField(max_length=50)),
                ('specie', models.CharField(max_length=100)),
                ('età', models.IntegerField(default=0)),
                ('descrizione', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Utente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cognome', models.CharField(max_length=100)),
                ('età', models.IntegerField(default=18)),
                ('email', models.CharField(max_length=400)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
