# Generated by Django 4.2.4 on 2023-08-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RichiestaAdozione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeCognome', models.CharField(max_length=300)),
                ('indirizzo', models.CharField(max_length=400)),
                ('emailNumeroDiTelefono', models.CharField(max_length=500)),
            ],
        ),
    ]
