# Generated by Django 4.2.4 on 2023-08-31 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_richiestaadozione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richiestaadozione',
            name='nomeCognome',
            field=models.CharField(max_length=320),
        ),
    ]
